# Generated by Django 5.1.3 on 2024-11-21 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('vacation_home', 'Vacation Home')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='property_photos/')),
                ('number_of_stars', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('number_of_bedrooms', models.PositiveIntegerField()),
                ('number_of_living_rooms', models.PositiveIntegerField()),
                ('number_of_bathrooms', models.PositiveIntegerField()),
                ('number_of_dining_rooms', models.PositiveIntegerField()),
                ('wifi_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_units_ready', models.PositiveIntegerField()),
                ('number_of_refrigerators', models.PositiveIntegerField()),
                ('number_of_tvs', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
