# Generated by Django 5.1.3 on 2024-11-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_property_options_alter_property_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furnishing_type',
            field=models.CharField(choices=[('luxurious', 'Luxuriously Furnished'), ('modest', 'Modestly Furnished')], default='modest', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyUnavailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.property')),
            ],
        ),
    ]
