# Generated by Django 5.1.3 on 2024-12-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_number_of_tvs_property_number_of_tvs1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='number_of_tvs1',
            new_name='number_of_tvs',
        ),
    ]
