# Generated by Django 5.1.3 on 2024-12-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_number_of_tvs1_property_number_of_tvs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
    ]
