# Generated by Django 5.1.3 on 2024-11-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_property_furnishing_type_propertyunavailabledate'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='property',
            name='number_of_stars',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
    ]
