# Generated by Django 5.1.3 on 2024-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_property_number_of_units_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='max_number_guests',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
