# Generated by Django 5.1.3 on 2024-11-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_property_max_number_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('vacation_house', 'Vacation House')], max_length=20),
        ),
    ]
