# Generated by Django 5.1.3 on 2024-12-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
    ]
