# Generated by Django 5.1.3 on 2024-11-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_property_property_type'),
    ]

    operations = [
       
    ]
