# Generated by Django 5.1.3 on 2024-12-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_property_image1_property_image2_property_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image1',
            field=models.ImageField(default=23, upload_to='properties/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='image2',
            field=models.ImageField(upload_to='properties/images/'),
        ),
    ]
