# Generated by Django 5.1.3 on 2024-12-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_property_image1_alter_property_image2'),
        ('profile', '0014_rename_username_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='profile.ownerprofile'),
        ),
        migrations.AlterField(
            model_name='property',
            name='wifi_speed',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
