# Generated by Django 5.1.3 on 2024-12-05 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_property_image1_alter_property_image2_and_more'),
        ('profile', '0018_rename_profile_picture_ownerprofile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='profile.ownerprofile'),
        ),
        migrations.AlterField(
            model_name='property',
            name='wifi_speed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
