# Generated by Django 5.1.3 on 2024-11-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='number_of_stars',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
