# Generated by Django 5.1.3 on 2024-12-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_property_image1_alter_property_image2_and_more'),
        ('management', '0012_property_owner_alter_property_number_of_stars'),
    ]

    operations = [
    ]
