# Generated by Django 5.1.3 on 2024-12-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='about_lodgini',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='management.property'),
        ),
    ]
