# Generated by Django 5.1.3 on 2024-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_ownerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
