# Generated by Django 5.1.3 on 2024-11-21 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_ownerprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
