# Generated by Django 5.1.3 on 2024-11-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_remove_userprofile_location_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
