# Generated by Django 5.1.3 on 2024-11-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_remove_ownerprofile_name_remove_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='phone_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
