# Generated by Django 5.1.3 on 2024-11-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
