# Generated by Django 5.1.3 on 2024-11-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_rename_name_ownerprofile_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='username',
            new_name='name',
        ),
    ]
