# Generated by Django 5.1.3 on 2024-11-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_alter_userprofile_managers_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
