# Generated by Django 5.1.3 on 2024-11-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_rename_username_ownerprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
