# Generated by Django 5.1.3 on 2024-12-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0015_alter_ownerprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_owner_pics/'),
        ),
    ]
