# Generated by Django 5.1.3 on 2024-12-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_alter_ownerprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_owner_pics/'),
        ),
    ]
