# Generated by Django 5.1.3 on 2024-12-03 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_alter_ownerprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerprofile',
            old_name='profile_picture',
            new_name='profilepicture',
        ),
    ]
