# Generated by Django 5.1.3 on 2024-12-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0015_alter_userprofile_email_alter_userprofile_username'),
        ('profile', '0018_rename_profile_picture_ownerprofile_profilepicture'),
    ]

    operations = [
    ]
